/**
 * Global feature importance, per model.
 *
 * GENERATED by reading `feature_importances_` off the trained .pkl files —
 * these are the models' own numbers, not estimates. Regenerate if a model is
 * ever retrained; nothing computes them at runtime.
 *
 * IMPORTANT — what these are and are not:
 *
 *   GLOBAL importance: how much each input shaped the model overall, across
 *   its whole training set. NOT per-patient attribution. This says "GGT drives
 *   the fatty liver model", never "GGT drove YOUR result". Per-patient
 *   attribution needs SHAP, a new dependency and a backend change that is out
 *   of scope at this range. Label it accordingly wherever it appears.
 *
 *   Decision D-2, option (a).
 *
 * Features the model ignored entirely (0%) are omitted — worth knowing, not
 * worth a bar of length zero. Note fatty liver uses only THREE of its thirteen
 * inputs, which is itself a finding.
 *
 * THE TWO HEPATITIS ENTRIES WERE REGENERATED FROM THE HCV MODELS on
 * 2026-08-10. Those models also take DERIVED inputs — APRI, ALBI_Score,
 * Bili_Alb_Ratio, Bilirubin_Albumin, Copper_Platelets — and the stage model
 * additionally takes `Status`, which is the status model's own verdict. All of
 * those are excluded here and the remainder renormalised to 100.
 *
 * That is a DISPLAY decision, not a data one: this chart pairs each key with
 * the value the CLINICIAN TYPED IN (`values[f.key]` in charts.tsx), and a
 * derived ratio has no typed value to sit beside. `Status` would be worse than
 * blank — it is an internal model input, and naming it on screen is exactly the
 * implementation vocabulary L-026 keeps off the interface.
 *
 * Recorded rather than hidden: before renormalising, `Hepatomegaly` alone
 * carried 35.6% of the stage model and `Status` 11.4%.
 */

export interface FeatureImportance {
  key: string
  /** Percent of total importance; each model's list sums to ~100. */
  pct: number
}

export const FEATURE_IMPORTANCE: Record<string, FeatureImportance[]> = {
  gate: [
    { key: 'bilirubin_direct', pct: 23.2 },
    { key: 'bilirubin', pct: 16.0 },
    { key: 'alp', pct: 11.3 },
    { key: 'alt', pct: 10.6 },
    { key: 'albumin', pct: 10.5 },
    { key: 'ast', pct: 9.7 },
    { key: 'total_proteins', pct: 9.7 },
    { key: 'ag_ratio', pct: 9.0 },
    { key: 'age', pct: 0.1 },
  ],
  cancer: [
    { key: 'cancer_history', pct: 27.7 },
    { key: 'genetic_risk', pct: 23.3 },
    { key: 'smoking', pct: 12.4 },
    { key: 'gender', pct: 12.1 },
    { key: 'bmi', pct: 7.2 },
    { key: 'age', pct: 6.1 },
    { key: 'alcohol', pct: 5.7 },
    { key: 'activity', pct: 5.5 },
  ],
  fatty_liver: [
    { key: 'ggt', pct: 62.4 },
    { key: 'alt', pct: 26.3 },
    { key: 'triglycerides', pct: 11.3 },
  ],
  hepatitis_stage: [
    { key: 'hepatomegaly', pct: 45.0 },
    { key: 'prothrombin', pct: 5.9 },
    { key: 'bilirubin', pct: 5.6 },
    { key: 'spiders', pct: 5.3 },
    { key: 'albumin', pct: 4.2 },
    { key: 'edema', pct: 4.2 },
    { key: 'triglycerides', pct: 4.0 },
    { key: 'copper', pct: 3.7 },
    { key: 'cholesterol', pct: 3.6 },
    { key: 'age', pct: 3.6 },
    { key: 'ascites', pct: 3.4 },
    { key: 'alp', pct: 3.0 },
    { key: 'platelets', pct: 3.0 },
    { key: 'gender', pct: 2.9 },
    { key: 'ast', pct: 2.5 },
  ],
  hepatitis_complications: [
    { key: 'edema', pct: 34.0 },
    { key: 'prothrombin', pct: 12.8 },
    { key: 'albumin', pct: 9.4 },
    { key: 'platelets', pct: 6.9 },
    { key: 'triglycerides', pct: 6.2 },
    { key: 'ast', pct: 5.6 },
    { key: 'alp', pct: 5.5 },
    { key: 'cholesterol', pct: 4.6 },
    { key: 'bilirubin', pct: 4.0 },
    { key: 'copper', pct: 4.0 },
    { key: 'age', pct: 3.6 },
    { key: 'gender', pct: 1.6 },
    { key: 'spiders', pct: 1.4 },
    { key: 'hepatomegaly', pct: 0.2 },
  ],
}
